name: Ozone FOSS E2E Tests

on:

  workflow_dispatch:
    inputs:
      e2e_base_url_input:
        description: 'O3 URL'
        required: true
      e2e_odoo_url_input:
        description: 'Odoo URL'
        required: true
      e2e_senaite_url_input:
        description: 'SENAITE URL'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Run E2E tests
        env:
          O3_DEV: '${{ github.event.inputs.e2e_base_url_input }}'
          ODOO_URL_DEV: '${{ github.event.inputs.e2e_odoo_url_input }}'
          SENAITE_URL_DEV: '${{ github.event.inputs.e2e_senaite_url_input }}'
          RUNNING_OZONE_ON_PRO: 'false'
        run: npm run fossE2ETests

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
