name: Slack Notifications

on:
  schedule:
    - cron: '0 1 * * 1,3,5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
         payload: |
           {
             "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.schedule.html_url || github.event.head_commit.url  }}",
             "blocks": [
               {
                 "type": "section",
                 "text": {
                           "type": "mrkdwn",
                           "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.schedule.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
